"""Initial migration - create all tables

Revision ID: 366f6842dc9c
Revises: 9959757709ec
Create Date: 2025-11-25 16:22:10.632535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '366f6842dc9c'
down_revision = '9959757709ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
