"""remove_duplicate_user_fields

Revision ID: ce7158b8e4aa
Revises: 62370bec924c
Create Date: 2025-12-13 17:18:38.413373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce7158b8e4aa'
down_revision = '62370bec924c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'degree')
    op.drop_column('users', 'year_of_study')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('year_of_study', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('degree', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
