"""add_user_degree_fields

Revision ID: d1d5f625fa4c
Revises: c71643c1030d
Create Date: 2025-12-13 16:33:43.278201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1d5f625fa4c'
down_revision = 'c71643c1030d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('degree', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('department_number', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('year_in_degree', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'year_in_degree')
    op.drop_column('users', 'department_number')
    op.drop_column('users', 'degree')
    # ### end Alembic commands ###
