"""add_email_verification_fields

Revision ID: 03699aa00a08
Revises: 366f6842dc9c
Create Date: 2025-12-12 12:22:19.721515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03699aa00a08'
down_revision = '366f6842dc9c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('email_verification_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('email_verification_token_expires', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verification_token_expires')
    op.drop_column('users', 'email_verification_token')
    op.drop_column('users', 'is_email_verified')
    # ### end Alembic commands ###
