"""update_material_types

Revision ID: 22c9fc4babb5
Revises: ce7158b8e4aa
Create Date: 2025-12-14 16:14:42.881900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22c9fc4babb5'
down_revision = 'ce7158b8e4aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
