"""remove material_id from comments make discussion_id required

Revision ID: 3046663d3acb
Revises: 1fa4f246c3de
Create Date: 2025-12-20 22:19:04.918203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3046663d3acb'
down_revision = '1fa4f246c3de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'discussion_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('fk_comments_material_id', 'comments', type_='foreignkey')
    op.drop_column('comments', 'material_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('material_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_comments_material_id', 'comments', 'materials', ['material_id'], ['id'])
    op.alter_column('comments', 'discussion_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
