"""add_material_id_to_discussions

Revision ID: 4c53d46fc3a8
Revises: 76fd0d7e1901
Create Date: 2026-01-01 14:47:25.125313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c53d46fc3a8'
down_revision = '76fd0d7e1901'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discussions', sa.Column('material_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'discussions', 'materials', ['material_id'], ['id'])

    # Add check constraint: discussion must belong to either course OR material (not both, not neither)
    op.create_check_constraint(
        'discussion_type_check',
        'discussions',
        '(course_id IS NOT NULL AND material_id IS NULL) OR (course_id IS NULL AND material_id IS NOT NULL)'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('discussion_type_check', 'discussions', type_='check')
    op.drop_constraint('discussions_material_id_fkey', 'discussions', type_='foreignkey')
    op.drop_column('discussions', 'material_id')
    # ### end Alembic commands ###
