"""add_view_count_to_materials

Revision ID: f64331fb0330
Revises: 4c53d46fc3a8
Create Date: 2026-01-04 14:55:42.786644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f64331fb0330'
down_revision = '4c53d46fc3a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('view_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materials', 'view_count')
    # ### end Alembic commands ###
