"""add_notifications_and_settings_tables

Revision ID: 9d9c655b3d7c
Revises: f64331fb0330
Create Date: 2026-01-04 15:48:30.461602

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9d9c655b3d7c'
down_revision = 'f64331fb0330'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create notification_settings table
    op.create_table('notification_settings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('comment_on_material_in_app', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('comment_on_material_email', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('comment_on_discussion_in_app', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('comment_on_discussion_email', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('reply_to_comment_in_app', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('reply_to_comment_email', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('material_rated_in_app', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('material_rated_email', sa.Boolean(), nullable=False, server_default='false'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_notification_settings_user_id'), 'notification_settings', ['user_id'], unique=False)

    # Update notifications table
    op.add_column('notifications', sa.Column('type', sa.Enum('COMMENT_ON_MATERIAL', 'COMMENT_ON_DISCUSSION', 'REPLY_TO_COMMENT', 'MATERIAL_RATED', name='notificationtype'), nullable=False))
    op.add_column('notifications', sa.Column('message', sa.Text(), nullable=False))
    op.add_column('notifications', sa.Column('email_sent', sa.Boolean(), nullable=False))
    op.add_column('notifications', sa.Column('related_comment_id', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('related_material_id', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('related_discussion_id', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('actor_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.drop_constraint('notifications_user_id_fkey', 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'notifications', 'discussions', ['related_discussion_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'notifications', 'comments', ['related_comment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'notifications', 'materials', ['related_material_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'notifications', 'users', ['actor_id'], ['id'], ondelete='CASCADE')
    op.drop_column('notifications', 'notification_type')
    op.drop_column('notifications', 'read_at')
    op.drop_column('notifications', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Revert notifications table changes
    op.add_column('notifications', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('read_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('notification_type', postgresql.ENUM('NEW_COMMENT', 'NEW_RATING', 'MENTION', 'NEW_MATERIAL', 'MESSAGE', 'SYSTEM', name='notificationtype'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key('notifications_user_id_fkey', 'notifications', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_column('notifications', 'actor_id')
    op.drop_column('notifications', 'related_discussion_id')
    op.drop_column('notifications', 'related_material_id')
    op.drop_column('notifications', 'related_comment_id')
    op.drop_column('notifications', 'email_sent')
    op.drop_column('notifications', 'message')
    op.drop_column('notifications', 'type')

    # Drop notification_settings table
    op.drop_index(op.f('ix_notification_settings_user_id'), table_name='notification_settings')
    op.drop_table('notification_settings')
    # ### end Alembic commands ###
